# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qqbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqqbot.proto\x12\x05proto\"\x1c\n\tNotifyReq\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x17\n\x04Resp\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x0cQQBotService\x12)\n\x06Notify\x12\x10.proto.NotifyReq\x1a\x0b.proto.Resp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qqbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYREQ']._serialized_start=22
  _globals['_NOTIFYREQ']._serialized_end=50
  _globals['_RESP']._serialized_start=52
  _globals['_RESP']._serialized_end=75
  _globals['_QQBOTSERVICE']._serialized_start=77
  _globals['_QQBOTSERVICE']._serialized_end=134
# @@protoc_insertion_point(module_scope)
