# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspider.proto\x12\x05proto\"\x1e\n\tSpiderReq\x12\x11\n\tis_mobile\x18\x01 \x01(\x08\"\x19\n\nSpiderResp\x12\x0b\n\x03url\x18\x01 \x01(\t2\x89\x01\n\rSpiderService\x12;\n\x12GetCNBingWallPaper\x12\x10.proto.SpiderReq\x1a\x11.proto.SpiderResp\"\x00\x12;\n\x12GetUSBingWallPaper\x12\x10.proto.SpiderReq\x1a\x11.proto.SpiderResp\"\x00\x42\x16Z\x14spider_pb/;spider_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024spider_pb/;spider_pb'
  _globals['_SPIDERREQ']._serialized_start=23
  _globals['_SPIDERREQ']._serialized_end=53
  _globals['_SPIDERRESP']._serialized_start=55
  _globals['_SPIDERRESP']._serialized_end=80
  _globals['_SPIDERSERVICE']._serialized_start=83
  _globals['_SPIDERSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
